name: Tests
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - release/**
jobs:
  phpunit:
    name: Jest unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Comment with Test Coverage
        uses: dkershner6/jest-coverage-commenter-action@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          test_command: "npm run test:ci"
